# NORMALIZATION PROBLEM 

In [1]:
import numpy as np 

X = np.random.rand(5,5)
print('Random X = \n', X)

X_mean = X.mean()
X_std = X.std()
X_normalized = (X - X_mean) / X_std

np.save('X_normalized.npy', X_normalized)

print('\nNormalized X = \n', X_normalized)

Random X = 
 [[0.72047248 0.76301327 0.63503249 0.20366651 0.51662868]
 [0.47903869 0.94632862 0.19805436 0.37048448 0.77732016]
 [0.82739072 0.21541867 0.23212586 0.55446696 0.90647601]
 [0.56399194 0.87322018 0.00103354 0.3898854  0.37759287]
 [0.45572228 0.75995618 0.922237   0.40487789 0.66291111]]

Normalized X = 
 [[ 0.65718998  0.82147253  0.32724075 -1.33859359 -0.13000701]
 [-0.27517076  1.52939348 -1.36026638 -0.69438165  0.87672241]
 [ 1.07008317 -1.2932095  -1.22869023  0.01611556  1.37549202]
 [ 0.05289879  1.24706579 -2.12111462 -0.61945987 -0.66693072]
 [-0.36521326  0.80966677  1.43635727 -0.56156239  0.43490147]]


# DIVISIBLE BY 3 PROBLEM:

In [18]:
squares = np.arange(1,101)**2
A = squares.reshape(10,10)

div_by_3 = A[A%3 == 0]

np.save('div_by_3.npy', div_by_3)

print(div_by_3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
