# NORMALIZATION PROBLEM 

In [5]:
import numpy as np 

X = np.random.rand(5,5)
print('Random X = \n', X)

X_mean = X.mean()
X_std = X.std()
X_normalized = (X - X_mean) / X_std

np.save('X_normalized.npy', X_normalized)

print('\nNormalized X = \n', X_normalized)

Random X = 
 [[0.82053733 0.77887772 0.51857879 0.5565555  0.81555634]
 [0.34499033 0.0241727  0.26398307 0.70970889 0.47025263]
 [0.70313796 0.26798383 0.45033211 0.32330574 0.73338424]
 [0.17786968 0.36931331 0.38219898 0.27693555 0.12160005]
 [0.91407336 0.27845827 0.73221701 0.80050689 0.678026  ]]

Normalized X = 
 [[ 1.28861441  1.12087289  0.07278481  0.22569723  1.26855855]
 [-0.62616543 -1.91793078 -0.95233943  0.84236605 -0.12179946]
 [ 0.81590834 -0.93623045 -0.20200901 -0.71347798  0.93769437]
 [-1.29907316 -0.52822949 -0.4763456  -0.90018654 -1.52564162]
 [ 1.66523525 -0.89405533  0.93299453  1.20796226  0.71479559]]


# DIVISIBLE BY 3 PROBLEM:

In [3]:
squares = np.arange(1,101)**2
A = squares.reshape(10,10)

div_by_3 = A[A%3 == 0]

np.save('div_by_3.npy', div_by_3)

print(div_by_3)

[   9   36   81  144  225  324  441  576  729  900 1089 1296 1521 1764
 2025 2304 2601 2916 3249 3600 3969 4356 4761 5184 5625 6084 6561 7056
 7569 8100 8649 9216 9801]
